CHANGELOG.md, docs/src/_css/custom.css, docs/src/reference/components/azure.md, docs/src/topics/deployment/config/azure.md, src/mach/templates/partials/endpoints/azure_frontdoor_endpoint.tf, tests/files/azure_config1_expected_mach-site-eu.json, tests/files/azure_config1_expected_mach-site-us.json
This PR will make it possible to have more control over the Frontdoor routing.
Since Frontdoor has to be deployed as 1 resource, it's not possible to define component-routes within the component.
Up until now MACH made educated guesses on what address to route to, what path to use, etc.
But in many cases these are not sufficient, and it would be desirable for a component to have some more control over routing (paths, protocols, health checks, etc).
This change will require each component that uses an `endpoint` to define a Terraform output like so;
At bare **minimum**
```hcl
output "azure_endpoint_main" {
value = {
address = azurerm_app_service.main.default_site_hostname
}
}
```
And could be extended with:
```hcl
output "azure_endpoint_main" {
value = {
address = …
```
=> Provide frontdoor routing details via component output

CHANGELOG.md, docs/src/reference/syntax/sites.md, src/mach/templates/partials/commercetools.tf, src/mach/types/sites.py, src/mach/validate.py, tests/unittests/test_validate.py
Add `tax_categories` for commercetools but do not break old `taxes` as to keep backward compatibility.
=> add commercetools tax_categories

CHANGELOG.md, README.md, docs/src/reference/cli.md, src/mach/commands.py, src/mach/terraform.py
This is so we can run security scanners like tfsec on downloaded modules as well without hitting providers api by using the plan command
=> added terraform init command support

cmd/generate.go, cmd/root.go, cmd/terraform.go, generator/writer.go, generator/writer_test.go, runner/apply.go, runner/exec.go
This command proxies the arguments to terraform in the generated path.
Useful for various debugging activities
=> Implement the `mach-composer terraform` command.

CHANGELOG.md, cmd/common.go, config/types_commercetools.go, docs/src/reference/syntax/sites.md
Creating frontend credentials is not an often used version, so it has been decided to deprecate it.
=> feat(commercetools frontend): deprecate this functionality

CHANGELOG.md, config/parse_test.go, config/types_config.go, updater/git.go
The docs specify components can specify a branch to follow. The current go-code only follows HEAD.
HEAD is maintained as default, but branch is now tracked correctly.
=> fix: use the branch configuration on component

internal/config/parse_test.go, internal/config/types_aws.go, internal/config/types_commercetools.go, internal/config/types_config.go, internal/config/types_global.go, internal/config/types_sentry.go, internal/config/types_site.go, internal/generator/generate_test.go, internal/generator/templates/component/commercetools_variables.tf, internal/generator/templates/config.tf, internal/generator/templates/services/aws/main.tf, internal/generator/templates/services/azure/frontdoor.tf, internal/generator/templates/services/commercetools/main.tf, internal/generator/templates/services/commercetools/stores.tf
- Fix bool attributes which are true by default not being set to false (aws.encrypt, commercetools.messages_enabled)
- Apply go style naming
- Add missing mach_composer.version yaml tag
- Fix some templates referencing to incorrect property names (caused by #181)
- Fix SentryConfigBase not being expanded within SentryConfig (#181)
- Fix commercetools variables and secrets not being parsed
=> Fix various issues

cmd/mach-composer/apply.go, cmd/mach-composer/common.go, cmd/mach-composer/components.go, cmd/mach-composer/generate.go, cmd/mach-composer/main.go, cmd/mach-composer/plan.go, cmd/mach-composer/sites.go, cmd/mach-composer/terraform.go, cmd/mach-composer/update.go
- Replaces `LoadConfigs()` with the newly added `LoadConfig()` under `cmd/`.
Also based on this change:
- Re-add support for `sites` command
- Re-add support for `components` command
Closes #177 
Closes #178 
Closes #179
=>  Load configuration from single file

cmd/mach-composer/cloudcmd/api_client.go, cmd/mach-composer/cloudcmd/component.go, go.mod, go.sum, internal/cloud/version.go, internal/updater/git.go
Add option to automatically detect the component version when registering a new version. It retrieves the current version from mcc and pushes commit metadata of the commits between the old and new version
=> Automatically detect the component version when registering a new version

internal/config/parse.go, internal/config/types_config.go, internal/generator/writer.go
When a variable file is encrypted with sops we need to copy the file to the generated output so that file can be read by the sops terraform provider.
=> Copy the variable files to the generate output

cmd/mach-composer/cloudcmd/component.go, cmd/mach-composer/cloudcmd/organization.go, cmd/mach-composer/cloudcmd/project.go, cmd/mach-composer/main.go, cmd/mach-composer/update.go, go.mod, go.sum, internal/cloud/version.go, internal/config/schemas/schema-1.yaml, internal/config/types.go, internal/gitutils/git.go, internal/gitutils/git_test.go, internal/runner/apply.go, internal/updater/changes.go, internal/updater/main.go, internal/updater/updates.go
This options uses mach composer cloud to fetch the latest component versions instead of relying on the git repositories.
=> Add `—cloud` option to `mach-composer update`

.changes/unreleased/Added-20230314-170347.yaml, cmd/mach-composer/cloudcmd/component.go, go.mod, internal/cloud/version.go, internal/gitutils/git.go, internal/gitutils/git_test.go
Add `--dry-run` and `--git-filter-paths` to `cloud register-component-version` command.  The `--git-filter-paths` argument can be used to limit the scope of the changes when working within monorepo's.
=> Add extra arguments to the `cloud register-component-version` cmd

.changes/unreleased/Fixed-20230316-085744.yaml, internal/gitutils/git.go, internal/gitutils/git_test.go
When calculating the differences between the last version and the
current version don't error when the last version is no longer existing.
This might be caused by a history rewrite or when a commit in a branch
was referenced
=> Don't error when a previous version is not found in the git repository

.changes/unreleased/Fixed-20230317-150045.yaml, internal/gitutils/diff.go, internal/gitutils/git.go
By filtering the git commits on paths we weren't able to find the last
version if that was filtered out. Instead loop through all commits and
implement the path matching ourselves. This should also workaround a
few bugs in the go-git implementation
=> Refactor matching if commits are relevant for path filter

.changes/unreleased/Fixed-20230717-161143.yaml, internal/config/parse.go, internal/config/parse_test.go, internal/config/utils.go, internal/config/utils_test.go, internal/updater/main.go, internal/updater/writer_config.go, internal/updater/writer_config_test.go, internal/updater/writer_sops.go
When the components.yaml is included via $ref syntax the mach-composer
update command didn’t work.
This commit updates the referenced file
=> Fix mach-composer update for $ref files

README.md, docs/src/howto/ci/github.md, docs/src/topics/deployment/components.md, docs/src/topics/deployment/config/index.md, docs/src/topics/development/environment.md, docs/src/tutorial/step-1-installation.md
This PR contains some minor tweaks to the documentation to:
- Update outdated references after the move from the @labd to @mach-composer org
- Make the capitalization of "GitHub" and "GitHub Actions" consistent with the rest of the docs
I expect to create another PR with some more substantial docs changes after I've had a chance to familiarize myself with the project more, but I figured it might be good to get this merged in the meantime.
=> Update docs after mach composer move between orgs

internal/config/parse.go, internal/config/parse_test.go, internal/config/utils.go, internal/config/utils_test.go, internal/updater/main.go
Currently, `components.$ref` reads the file from the location of `main.yaml`, but `mach_composer.variables_file` reads it from where the binary is executed (cwd). This PR makes `components.$ref` read the file from cwd as well, bringing its behavior in line with that of `mach_composer.variables_file`.
Fixes #283
- `components.$ref` now reads the file using cwd as the root, making it consistent with the `mach_composer.variables_file` import behavior.
=> Fix inconsistent yaml file import root

.github/workflows/release.yaml
Currently, we are using not the latest path versions for terraform
Updated to latest patch releases of Terraform 1.3.x and added latest 2 minor versions
=> Update terraform versions in release pipeline

.changes/unreleased/Fixed-20230928-155812.yaml, internal/gitutils/diff.go
Fixes #309
Fixed iterating until the beginning if the first commit is not found in paths.
=> Fixed iterating until beginning if commit not found in paths.

.changes/unreleased/Fixed-20240416-103813.yaml, internal/generator/component.go
**New PR with fix for resolving local windows paths**
Previous PR: https://github.com/mach-composer/mach-composer-cli/pull/323
I've tailored this fix specifically for Windows to simplify the acceptance process for you. It would be greatly appreciated if this could be merged soon, as I need to compile my own executable to utilize the latest release.
=> Fix: Escape backslashes in module source path for Windows

.changes/unreleased/Added-20240917-115620.yaml, internal/cmd/update.go, internal/updater/updater.go, internal/updater/updates.go
Add `--git-fallback` option to the `update` command to make the fallback explicit and only when needed/desired.
=> feat: add git fallback option to update command

.changes/unreleased/Fixed-20240930-131637.yaml, internal/updater/updates.go
In case of hotfix releases we switch to a different `branch` name but current versions defined in our component definitions are from the previous branch (`main` for example).
When performing `mach-composer update` it correctly retrieves a new version from Mach Cloud but fails fetching commits between old and new (because old does not exist on the new branch name).
This change will make sure this error is logged, but the process itself is not aborted and we can continue updating components.
=> fix: continue with error log when commits between versions cannot be found

.changes/unreleased/Fixed-20250110-144620.yaml, internal/generator/component.go, internal/generator/component_test.go
Fixes #472
-  because slices are not by default sorted, we have to sort them before compacting when generating the remote state components
=> fix: added sorting of state identifiers before compacting

.changes/unreleased/Fixed-20250225-083100.yaml, internal/gitutils/git.go
Instead of sending a short hash to mach composer cloud, use the full
hash
=> feat: use full-commit hash for mach-composer cloud

internal/generator/templates/terraform.tmpl
There has been a 1.0.0 release for the provider so we don't get any update anymore.
=> Update sops provider version

.changes/unreleased/Dependency-20250512-230643.yaml, .changes/unreleased/Fixed-20250512-224649.yaml, .github/workflows/release.yaml
The release GitHub action is broken now because of a breaking change in `docker/bake-action` GitHub action after upgrading from v5 to v6.
- Added `cwd://` prefix to the bake-file reference in the GitHub action.
- Added terraform 1.11.4 to build matrix
=> fix(ci): add cwd prefix to bake-file reference

.changes/unreleased/Added-20250919-155624.yaml, docs/src/howto/cli/filtering-commands.md, docs/src/reference/cli/mach-composer.md, docs/src/reference/cli/mach-composer_apply.md, docs/src/reference/cli/mach-composer_init.md, docs/src/reference/cli/mach-composer_plan.md, docs/src/reference/cli/mach-composer_show-plan.md, docs/src/reference/cli/mach-composer_terraform.md, docs/src/reference/cli/mach-composer_validate.md, internal/cmd/apply.go, internal/cmd/common.go, internal/cmd/init.go, internal/cmd/plan.go, internal/cmd/show-plan.go, internal/cmd/terraform.go, internal/cmd/validate.go, internal/graph/mocks.go, internal/graph/node.go, internal/runner/filter.go, internal/runner/graph.go, internal/runner/graph_test.go, internal/runner/runner.go
=> feat: added site pruning logic
