mach-composer/mach-composer-cli

CHANGELOG.md
docs/src/reference/cli.md
src/mach/commands.py
src/mach/terraform.py

We sometimes need to clean out developer accounts this would make it much easier to cleanup the mach resources.

add destroy flag to plan and apply command

---

src/mach/updater.py

Thread based approach for faster update check

---

generator/templates/component/commercetools_variables.tf

fix store definitions

---

CHANGELOG.md
generator/filters.go
generator/templates/config.tf

Backporting https://github.com/labd/mach-composer/commit/d199fea87f13df49f967b11dcde629d7056c1aa0 from 1.2 to 2.2

Add custom provider version operator

---

internal/config/parse.go
internal/config/parse_test.go
internal/config/schemas/schema-1.yaml

Supporting this config width is another challenge and something we might want to think about.
See #192

Add support for $(include()) in the components block

---

tests/files/aws_config1_expected_mach-site-eu.json
tests/files/aws_config1_expected_mach-site-us.json
tests/files/azure_config1_expected_mach-site-eu.json
tests/files/azure_config1_expected_mach-site-us.json
tests/files/config_w_variables_expected_mach-site-eu.json

This fixes the unittests for #203

Fix unittests

---

cmd/mach-composer/schema.go
internal/config/parse.go
internal/config/parse_test.go
internal/config/schemas/schema-1.yaml
internal/config/utils.go
internal/config/validate.go

This follows the syntax supported by openapi and json schemas

Support $ref: “file#target” for including other files

---

.changes/unreleased/Added-20230307-161000.yaml
cmd/mach-composer/apply.go
cmd/mach-composer/common.go
cmd/mach-composer/completion.go
cmd/mach-composer/components.go
cmd/mach-composer/generate.go
cmd/mach-composer/init.go
cmd/mach-composer/plan.go
cmd/mach-composer/show-plan.go
cmd/mach-composer/sites.go
cmd/mach-composer/terraform.go
cmd/mach-composer/update.go

This adds auto-complete to the config files, variable files and sites and component arguments

Improve support for shell auto completion

---

go.mod
go.sum
internal/config/parse.go
internal/config/parse_global.go
internal/config/parse_test.go
internal/config/schemas/schema-1.yaml
internal/config/types.go
internal/config/validate.go
internal/generator/generate.go
internal/generator/generate_test.go
internal/generator/writer.go
internal/state/aws.go
internal/state/azure.go
internal/state/gcp.go
internal/state/local.go
internal/state/renderer.go
internal/state/repository.go
internal/state/schema.go
internal/state/schemas/aws.schema.json
internal/state/schemas/azure.schema.json
internal/state/schemas/gcp.schema.json
internal/state/schemas/local.schema.json
internal/state/schemas/terraform_cloud.schema.json
internal/state/terraform_cloud.go
internal/utils/template.go

Also added terraform cloud as option

Added state generation directly into cli

---

.changes/unreleased/Fixed-20230914-161052.yaml
cmd/mach-composer/common.go
cmd/mach-composer/completion.go
internal/cloud/resolver.go
internal/config/hash.go
internal/config/parse.go
internal/config/parse_site.go
internal/config/parse_test.go
internal/config/types.go
internal/generator/writer.go
internal/gitutils/git.go
internal/lockfile/get.go
internal/lockfile/get_test.go
internal/lockfile/lockfile.go
internal/lockfile/lockfile_test.go
internal/lockfile/testdata/faulty.yaml
internal/lockfile/testdata/ok.yaml
internal/lockfile/write.go
internal/lockfile/write_test.go
internal/runner/init.go
internal/updater/changes.go
internal/updater/main.go
internal/updater/updates.go
internal/updater/writer_config_test.go

Fixes #241 
-  Reworked lockfile interpolation to take into consideration $LATEST version

241 fix check if yaml is changed when using $latest

---

.changes/unreleased/Fixed-20230926-164441.yaml
internal/config/parse.go
internal/config/parse_components.go
internal/config/parse_test.go
internal/config/utils.go
internal/config/utils_test.go
internal/updater/updater.go
internal/updater/writer_config.go

Fixes #278
-  fix usage of include in update

278 fix include usage when running mach composer update

---

.changes/unreleased/Added-20230926-150327.yaml
.changes/unreleased/Fixed-20230926-150342.yaml
go.mod
go.sum
internal/cli/formatter.go
internal/gitutils/git.go
internal/updater/changes.go
internal/updater/updates.go

Fixes #149 
Fixes #279 
-  Fixed issue with tag not being parsed correctly
- Added linked tags to update output

Fixed issue with tags not being parsed, added potential tags to output

---

.changes/unreleased/Fixed-20230929-085834.yaml
internal/config/parse.go
internal/config/parse_test.go
internal/config/utils.go
internal/config/utils_test.go
internal/config/validate.go
internal/updater/updater.go
internal/variables/main.go
internal/variables/main_test.go

283 components$ref reads file from location of mainyaml but mach composervariables file reads from where binary is executed

---

.changes/unreleased/Fixed-20230929-111318.yaml
internal/generator/writer.go

Fixes #312 
Create a directory path for the destination file if missing.

Fix for variables_file containing a directory

---

.changes/unreleased/Added-20231116-160541.yaml
Taskfile.yaml
cmd/mach-composer/plan.go
cmd/mach-composer/show-plan.go
cmd/mach-composer/terraform.go
cmd/mach-composer/update.go
internal/cli/errors.go
internal/config/config.go
internal/config/deployment.go
internal/config/parse.go
internal/config/parse_test.go
internal/config/raw.go
internal/config/schemas/schema-1.yaml
internal/config/site.go
internal/dependency/graph_test.go
internal/runner/apply.go
internal/runner/batch.go
internal/runner/exec.go
internal/runner/init.go
internal/runner/plan.go
internal/runner/proxy.go
internal/runner/show.go
internal/utils/exec.go

Fixes #336
-  Added parallelism to runners

feat: added parallelism to runners

---

.changes/unreleased/Added-20231212-093337.yaml
cmd/mach-composer/plan.go
go.mod
go.sum
internal/plugins/config.go
internal/runner/apply.go
internal/runner/exec.go
internal/runner/init.go
internal/runner/mocks_test.go
internal/runner/plan.go
internal/runner/plan_test.go
internal/runner/proxy.go
internal/runner/show.go
internal/runner/utils.go
internal/state/local.go

Fixes #
-  adds -lock=false option for plan

Mc 169 support lock false on mach composer plans

---

.changes/unreleased/Fixed-20240223-110140.yaml
internal/graph/dependency_test.go
internal/graph/site.go
internal/graph/site_component.go
internal/graph/site_component_test.go
internal/graph/site_test.go
internal/utils/terraform.go

-  Turned missing hash into a warning

fix: made hash check more permissive for site components

---

.changes/unreleased/Updated-20240305-131421.yaml
internal/config/component.go
internal/config/source.go
internal/config/source_test.go
internal/generator/component.go
internal/gitutils/git.go
internal/graph/hash.go
internal/graph/hash_test.go
internal/graph/site_component_test.go
internal/graph/site_test.go
internal/updater/updates.go

Fixes #
-  Improved source handling

Rd 231 allow using of s3 and gcs buckets as terraform source

---

.changes/unreleased/Fixed-20240412-145530.yaml
internal/graph/dependency.go
internal/graph/hash.go
internal/graph/hash_test.go
internal/graph/project.go
internal/graph/site.go
internal/graph/site_component.go
internal/graph/testdata/variables-1.yaml
internal/graph/testdata/variables-2.yaml
internal/utils/hash.go

Rd 357 change detection should also occur when sop file has changed

---

.changes/unreleased/Fixed-20240426-121328.yaml
internal/cloud/client.go
internal/cloud/resolver.go
internal/updater/updates.go
internal/updater/updates_test.go

Fixes #398 
-  Added better logging around using $LATEST in update --cloud

fix: added more concise logging around using $LATEST with update --cloud

---

.changes/unreleased/Added-20240725-092302.yaml
internal/cmd/cloudcmd/component.go

feat: added option to set branch on component version register

---

.changes/unreleased/Fixed-20240906-140210.yaml
internal/cmd/testdata/cases/generate/azure-basic/expected/main/test-1/component-1/main.tf
internal/cmd/testdata/cases/generate/azure-basic/expected/main/test-1/main.tf
internal/state/azure.go
internal/state/azure_test.go
internal/state/schemas/azure.schema.json

fix: added all azurem backend options

---

.changes/unreleased/Fixed-20241210-100157.yaml
internal/cli/errors.go
internal/runner/graph.go
internal/utils/exec.go

fix: improved logging returns

---

.changes/unreleased/Fixed-20250130-095453.yaml
internal/config/source.go
internal/config/source_test.go

fix: added smarter interpolation of git-based module sources

---

.github/workflows/pull-request.yaml
.golangci.yml
Taskfile.yaml

fix: fixed linting

---

go.mod
go.sum
internal/cmd/cloudcmd/api_client.go

feat: updated sdk

---

.changes/unreleased/Added-20250407-170141.yaml
.changes/unreleased/Fixed-20250408-080631.yaml
.golangci.yml

fix: updated golang lint config

---

.changes/unreleased/Fixed-20250410-092029.yaml
internal/cloud/resolver.go

fix: better error handling when resolving component version

---

.changes/unreleased/Fixed-20250704-113733.yaml
internal/cmd/cloudcmd/api_client.go
internal/cmd/cloudcmd/component.go
internal/cmd/cloudcmd/organization.go
internal/cmd/cloudcmd/project.go
internal/cmd/cloudcmd/utils.go

fix: fixed table generation
